# create secrets manually to avoid hardcoding secrets into manifests
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-avenue
type: Opaque
stringData:
  APP_SECRET: "your-app-secret"
  JWT_SECRET: "your-jwt-secret"
